### PR TITLE
Respeccify & import readme

### PR DESCRIPTION
**Pull request by clehner**
Convert the web page to use [Respec](https://respec.org/docs/) like other CG docs. Add some spec text.

Structure is adjusted, and references are improved.

Marking sections as normative vs. informative could still be improved. This currently defaults them all to normative.

Content changes are in 26486f996595446ec8e00c507a086641d2981a1c; indentation and spaces only are changed in cc1c84e070f8b23045eee91be4894c0ab73276d3.

License and readme content are imported in 720288b from the `cacao-zcap-rs` repo where they are being removed in https://github.com/spruceid/cacao-zcap-rs/pull/15.

Added Respec validation GitHub Action based on https://github.com/w3c/spec-prod/blob/main/docs/examples.md#run-as-a-validator-on-pull-requests

Preview: https://demo.didkit.dev/2022/04/21/cacao-zcap-pr-1.html

### CODE REVIEW

**Review by awoie — COMMENTED** [review]
have we used CC BY 4.0 in other projects before?

**Comment by clehner** [comment]
@awoie
I'm not sure, except that it was added in https://github.com/spruceid/cacao-zcap-rs/pull/1.

It's the default in Respec when using `specStatus: "unofficial"`: https://respec.org/docs/#specStatus
e.g. as seen in https://or13.github.io/lds-blockchain2021/, https://or13.github.io/lds-pgp2021/ and https://w3c-ccg.github.io/vdl-vocab/.

When specStatus is changed to e.g. `CG-DRAFT`, that changes to a reference to W3C Community Contributor License Agreement (CLA) (https://www.w3.org/community/about/agreements/cla/, https://www.w3.org/community/about/agreements/cla-deed/).
e.g. as in https://w3c-ccg.github.io/lds-ed25519-2020/, https://w3c-ccg.github.io/data-integrity-spec/.

If/when it goes into a Working Group, it changes to a https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document.

**Review by awoie — APPROVED** [review]
lgtm

**Comment by clehner** [comment]
Rebased and squashed some commits (26486f996595446ec8e00c507a086641d2981a1c..1426089d4a79f024d2f2de963afaab5c4a9aeae2 -> d4eaeb831e3c3c37d6e9bbd3f830d0fa5c0b1e06..3c62c1be1e7837156e1ca2ea32622775a3279572)

**Pull request merged**
