### PR TITLE
Structure CACAO statement to contain actions

### PR DESCRIPTION
**Pull request by clehner**
Re: https://github.com/spruceid/cacao-zcap-rs/issues/9#issuecomment-1098302556, https://github.com/spruceid/cacao-zcap-rs/issues/9#issuecomment-1098304811

Make the statement string match a format. The format begins with a string "Authorize action ". Following that is an optional part with the list of actions (`allowedAction` delegation property). Finally, the remainder of the string is an optional unstructured part, which is used as the `cacaoZcapSubstatement` delegation property).

Preview: https://demo.didkit.dev/2022/04/14/cacao-zcap-action-substmt.html#statement-actions-mapping
Preview with Respec (#1): https://demo.didkit.dev/2022/04/14/cacao-zcap-action-substmt-respec.html#statement-actions-mapping (branch `feat/action-substmt-respec`)

### CODE REVIEW

**Comment by cobward** [comment]
Mostly LGTM. I'm just wondering whether we want the colon or not. It does restrict how the substatement can be used. For example, we might want to have something that reads more naturally:
```
Authorize action (read, write) on your Kepler orbit for the duration of the session.
```
vs.
```
Authorize action (read, write): Allow access to your Kepler orbit for the duration of the session.
```

**Review by chunningham — APPROVED** [review]
looks super reasonable, re: the colon I think its ok either way, omitting can still allow services to add it, but I do appreciate a clear separator in this position

**Review by awoie — APPROVED** [review]
lgtm but i think we should sync with the 3box/Ceramic folks on this, especially if we wanna create something that can be used by different projects following CACAO/CASA specs. But we can merge this.

**Comment by clehner** [comment]
The colon separator is supposed to signify the separation between the part of the statement that is structured by this specification, and the part that is unstructured (although it could be structured by an application, but this specification just treats it as a string.
My concern about removing the separator is that it could be ambiguous and someone signing a statement might think that the whole statement has a particular meaning based on its text, when in fact the first part does but the remainder is arbitrary.
Agreed that it would be good to discuss with CASA, Ceramic/3Box, and/or other implementers.

**Comment by cobward** [comment]
That makes a lot of sense!

**Pull request merged**
